version: '3'

services:
  task3_image:
    image: ${TASK3_IMAGE}
    deploy:
      replicas: 5
    ports:
      - ${TASK3_IMAGE_PORTS}
    restart: always


  java_app:
    image: ${JAVA_APP}
    ports:
        - "8888:8080"
    depends_on:
      - db

  db:
     image: ${DB_IMAGE}
     environment:
      - POSTGRES_DB=${pg_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
