name: Docker Image CI

on:
push:
  branches: [ main ]
pull_request:
  branches: [ main ]

jobs:

build:

  runs-on: ubuntu-latest

  steps:
  -
    name: Checkout
    uses: actions/checkout@v2
  -
    name: Login Docker Hub
    uses: docker/login-action@v1
    with:
      username: ${{ secrets.DOCKER_LOGIN }}
      password: ${{ secrets.DOCKER_PASSWORD}}
  -
    name: Build and Push
    uses: docker/build-push-action@v2
    with:
      file: Task4/Dockerfile
      push: true
      tags: serbor/task:latest
